[package]
name = "systems_wasm"
version = "0.1.0"
authors = ["FlyByWire Simulations"]
edition = "2021"

[lib]
test = false

[dependencies]
uom.workspace = true
systems = { path = "../systems" }
msfs = { git = "https://github.com/flybywiresim/msfs-rs", branch = "main" }
rustc-hash = "2.1.1"
enum_dispatch = "0.3.7"
serde = "1.0"
serde_json = "1.0"
