blank_issues_enabled: false
- name: Support on GitHub
  url: https://github.com/flybywiresim/a32nx/discussions
  about: Find your question already answered or share it with the github community
- name: Support on Discord
  url: https://discord.com/channels/738864299392630914/785976111875751956
  about: Ask questions directly to our support on discord
