[package]
name = "systems"
version = "0.1.0"
authors = ["FlyByWire Simulations"]
edition = "2021"

[dependencies]
uom.workspace = true
rand.workspace = true
rand_distr = "0.5.1"
num-derive = "0.4.2"
num-traits = "0.2.19"
nalgebra = "0.33.0"
bounded-vec-deque = "0.1.1"
fxhash = "0.2.1"
bitflags = "2.9.1"

[dev-dependencies]
ntest.workspace = true
rstest.workspace = true
