[package]
name = "a320_systems"
version = "0.1.0"
authors = ["FlyByWire Simulations"]
edition = "2021"

[dependencies]
uom = "0.36.0"
nalgebra = "0.25.0"
ntest = "0.7.2"
systems = { path = "../../../../../fbw-common/src/wasm/systems/systems" }

[dev-dependencies]
rstest = "0.10.0"
rand = "0.8.0"
rand_pcg = "0.3.1"
