[package]
name = "a380_systems"
version = "0.1.0"
authors = ["FlyByWire Simulations"]
edition = "2021"

[dependencies]
bitflags = "2.9.1"
uom.workspace = true
nalgebra = "0.33.0"
fxhash = "0.2.1"
rand.workspace = true
serde = { version = "1.0.215", features = ["derive"] }
serde_with = { version = "3.11.0" }
toml = { version = "0.9.6", default_features = false, features = ["std", "serde", "parse"] }
systems = { path = "../../../../../fbw-common/src/wasm/systems/systems" }
enum-map = "2.7"

[dev-dependencies]
ntest.workspace = true
rstest.workspace = true
rand_pcg = "0.9.0"
